<<<<<<< HEAD
## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: tomorrow-night # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : https://erowz.github.io # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : La blogo de "Y Kaj Nai"
description: > # this means to ignore newlines until "Language & timezone"
  嚴與渿的博客 | Blog


## => Language and Timezone
##############################
lang: zh # the language of your site, default as "en"
timezone:	Asia/Shanghai # see https://en.데이터 싸이언티스트와 데이터 애널리스트, 데이터 엔지니어, 비즈니스 애널리스트wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : # "person" (default), "organization"
  name      : Erowz
  url       :
  avatar    : # path or url of avatar image (square)
  bio       : 嚴與渿的博客 | Blog
  email     :
  facebook  : # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram  : erowz # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium    : # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  zhihu     : wassup-57 # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  linkedin  : # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github    : erowz # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: erowz
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)
  about   : /about.xml


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->
excerpt_type: html # text (default), html

## license
## license: CC-BY-ND-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: true # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: true # false (default), true

## Chart
chart: true # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: addthis # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: ra-5f1c0ffa0adb6f6a # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
  provider:  false # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository  : # GitHub repo
    owner       : # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : # LeanCloud App id
    app_key     : # LeanCloud App key
    placeholder :  # Prompt information
    visitor     : # false (default)
    meta        :  # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
  provider: # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    :  # LeanCloud App id
    app_key   :  # LeanCloud App key
    app_class : # LeanCloud App class


## => Search 
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : # Google Analytics id for the site
    anonymize_ip:  # Anonymize IP tracking for Analytics

## Google Font
google_fonts : 

## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : /:categories/:title

## => Dev
############################## 
# show_drafts : true

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: false
      aside:
        toc: true
      sidebar:
        nav: nav-zh
      show_edit_on_github: false
      show_subscribe: false
      pageview: true
      fullwidth: true
      imgpath: "/assets/images"
  - scope:
      path: "category"
    values:
      layout: category
      sidebar:
        nav: nav-zh


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
=======
# Site settings
title: La blogo de "Y Kaj Nai"
title-alias: La blogo de "Y Kaj Nai"
SEOTitle: 嚴與渿的博客 | Blog
header-img: "img/blue.jpg"
email: olwreeass@gmail.com
description: "嚴與渿的博客" 
keyword: "嚴與渿 读书笔记 左传 现代汉语 思考 Blog erowz"
url: "https://erowz.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: true
email_address: olwreeass@gmail.com
# weibo_username:     Thistledown
zhihu_username: wassup-57/activities
github_username: erowz
# twitter_username:  MyThistledown
#facebook_username:  

# Data
gavatar: img/favicon.png # 浏览器地址栏小图标，可自定义更改
favicon: img/favicon.png # 浏览器地址栏小图标，可自定义更改


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


#Comment settings
# Disqus settings
# disqus_username: Thistledown

# Duoshuo settings
#duoshuo_username: Thistledown
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Publish posts or collection documents with a future date.
future: true

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "往来日久，迷恋不已。"
sidebar-avatar: /img/favicon.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Comments 
valine_comment:
    enable: true
    leancloud_appid: 7hgyMrKUuyLB2dXPeeia9O72-gzGzoHsz
    leancloud_appkey: bSWXyG6X950FhYGplIvUhvKb
    placeholder: "点击评论，记得输入上方的昵称喔~"


# Analytics and webmaster tools stuff goes here
google_analytics: G-YX6ZS8S1CY  # 填写你  google_analytics id
google_verify:

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true




# Friends
friends: [
     {
         title: "中国哲学书电子化计划",
         href: "https://ctext.org/zhs"
     },{
         title: "白雲深處人家 | 道学",
         href: "http://www.homeinmists.com/index.htm"
     }
 ]
theme: jekyll-theme-cayman
>>>>>>> 88b2943ca25fe536c314e5a05e2fc0c89e2a0433
